# Generated by Django 5.0.4 on 2024-05-06 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataInsight', '0003_rename_doctor_address_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('plan_type', models.CharField(max_length=100)),
                ('plan_id', models.CharField(max_length=100, unique=True)),
                ('non_members_number', models.CharField(max_length=100)),
                ('members_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BenefitsAndCosts',
            fields=[
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dataInsight.planoverview')),
                ('total_monthly_premiums', models.DecimalField(decimal_places=2, max_digits=10)),
                ('health_premiums', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drug_premiums', models.DecimalField(decimal_places=2, max_digits=10)),
                ('standard_part_b_premiums', models.DecimalField(decimal_places=2, max_digits=10)),
                ('part_b_premium_reductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('health_deductibles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drug_deductibles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_pay_for_health_services', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraBenefits',
            fields=[
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dataInsight.planoverview')),
                ('primary_doctor_visits', models.CharField(max_length=255)),
                ('specialists_visits', models.CharField(max_length=255)),
                ('diagnostics_test_procedures', models.CharField(max_length=255)),
                ('lab_services', models.CharField(max_length=255)),
                ('diagnostic_radiology_services', models.CharField(max_length=255)),
                ('outpatient_x_rays', models.CharField(max_length=255)),
                ('emergency_cares', models.CharField(max_length=255)),
                ('urgent_cares', models.CharField(max_length=255)),
                ('inpatient_hospital_coverages', models.CharField(max_length=255)),
                ('outpatient_hospital_coverages', models.CharField(max_length=255)),
                ('skilled_nursing_facilities', models.CharField(max_length=255)),
                ('preventive_services', models.CharField(max_length=255)),
                ('ground_ambulances', models.CharField(max_length=255)),
                ('occupational_therapy_visits', models.CharField(max_length=255)),
                ('physical_therapy_visits', models.CharField(max_length=255)),
                ('chemotherapy_drugs', models.CharField(max_length=255)),
                ('other_part_b_drugs', models.CharField(max_length=255)),
                ('part_b_insulins', models.CharField(max_length=255)),
                ('hearing_exams', models.CharField(max_length=255)),
                ('fitting_or_evaluations', models.CharField(max_length=255)),
                ('hearing_aids', models.CharField(max_length=255)),
                ('oral_exams', models.CharField(max_length=255)),
                ('cleanings', models.CharField(max_length=255)),
                ('fluoride_treatments', models.CharField(max_length=255)),
                ('dental_x_rays', models.CharField(max_length=255)),
                ('non_routine_services', models.CharField(max_length=255)),
                ('diagnostic_services', models.CharField(max_length=255)),
                ('restorative_services', models.CharField(max_length=255)),
                ('endodontics', models.CharField(max_length=255)),
                ('periodontics', models.CharField(max_length=255)),
                ('extractions', models.CharField(max_length=255)),
                ('prosthodontics_and_other_services', models.CharField(max_length=255)),
                ('routine_eye_exams', models.CharField(max_length=255)),
                ('contact_lenses', models.CharField(max_length=255)),
                ('eyeglasses', models.CharField(max_length=255)),
                ('eyeglasses_frames_only', models.CharField(max_length=255)),
                ('eyeglasses_lenses_only', models.CharField(max_length=255)),
                ('upgrades', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlanAddresses',
            fields=[
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dataInsight.planoverview')),
                ('plan_addresses', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DrugCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_level', models.IntegerField()),
                ('initial_coverage_phases', models.CharField(max_length=255)),
                ('gap_coverage_phases', models.CharField(max_length=255)),
                ('catastrophic_coverage_phases', models.CharField(max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataInsight.planoverview')),
            ],
        ),
    ]
