# Generated by Django 5.0.4 on 2024-05-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataInsight', '0004_planoverview_benefitsandcosts_extrabenefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitsandcosts',
            name='drug_deductibles',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='benefitsandcosts',
            name='drug_premiums',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='benefitsandcosts',
            name='health_deductibles',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='benefitsandcosts',
            name='health_premiums',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='benefitsandcosts',
            name='max_pay_for_health_services',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='benefitsandcosts',
            name='part_b_premium_reductions',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='benefitsandcosts',
            name='standard_part_b_premiums',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='benefitsandcosts',
            name='total_monthly_premiums',
            field=models.CharField(max_length=255),
        ),
    ]
